name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

  test-node:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [22, 24]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build npm package
        run: deno run -A scripts/build_npm.ts

      - name: Install dependencies
        working-directory: ./npm
        run: npm install

      - name: Run Node.js tests
        working-directory: ./npm
        run: npm test

  test-bun:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Build npm package
        run: deno run -A scripts/build_npm.ts

      - name: Install dependencies
        working-directory: ./npm
        run: bun install

      - name: Run Bun tests
        working-directory: ./npm
        run: bun run test_runner.js
